version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: tc_iot-grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ~/grafana_data:/vol01/Docker/monitoring